openlane PDNsim changes
RTimothyEdwards/open_pdks pull request #349
Opened 2023-02-07 18:35 UTC by kareefardi

\+ add `VDD_PIN_VOLTAGE` and `GND_PIN_VOLTAGE` needed by PDNsim for ir drop analysis
\- remove `sky130_fd_sc_hvl__tt_025C_3v30_lv1v80` from `LIB_SYNTH` as it breaks abc in yosys and I don't think level shifters are needed for synth (if I understand correctly that this lib is for level shifters)

2023-02-08 14:37 UTC, RTimothyEdwards requested changes
It appears that in `sky130_fd_sc_hvl/config.tcl` you are setting the pin voltage variables inside the EF_FORMAT block (which is used by nobody).  It should be moved outside the block.  Only things (mainly paths) that are different between EF_FORMAT = TRUE and EF_FORMAT = FALSE should be inside such an #ifdef block.

2023-02-09 12:56 UTC, kareefardi commented
Thanks for catching that. Update pushed

2023-02-10 14:01 UTC, RTimothyEdwards approved these changes
Looks good to me.

2023-02-10 14:02 UTC, RTimothyEdwards commented
Pulled and merged.  Mirror site will update tonight.

2023-02-10 14:02 UTC, closed without merging